export const SEND_COMMAND_REQUEST = '@@resolve/SEND_COMMAND_REQUEST'
export const SEND_COMMAND_SUCCESS = '@@resolve/SEND_COMMAND_SUCCESS'
export const SEND_COMMAND_FAILURE = '@@resolve/SEND_COMMAND_FAILURE'

//

export const SUBSCRIBE_TOPIC = '@@resolve/SUBSCRIBE_TOPIC'
export const UNSUBSCRIBE_TOPIC = '@@resolve/UNSUBSCRIBE_TOPIC'

//

export const CONNECT_VIEWMODEL = '@@resolve/CONNECT_VIEWMODEL'
export const DISCONNECT_VIEWMODEL = '@@resolve/DISCONNECT_VIEWMODEL'

export const LOAD_VIEWMODEL_STATE_REQUEST =
  '@@resolve/LOAD_VIEWMODEL_STATE_REQUEST'
export const LOAD_VIEWMODEL_STATE_SUCCESS =
  '@@resolve/LOAD_VIEWMODEL_STATE_SUCCESS'
export const LOAD_VIEWMODEL_STATE_FAILURE =
  '@@resolve/LOAD_VIEWMODEL_STATE_FAILURE'

export const DROP_VIEWMODEL_STATE = '@@resolve/DROP_VIEWMODEL_STATE'

//

export const CONNECT_READMODEL = '@@resolve/CONNECT_READMODEL'
export const DISCONNECT_READMODEL = '@@resolve/DISCONNECT_READMODEL'

export const LOAD_READMODEL_STATE_REQUEST =
  '@@resolve/LOAD_READMODEL_STATE_REQUEST'
export const LOAD_READMODEL_STATE_SUCCESS =
  '@@resolve/LOAD_READMODEL_STATE_SUCCESS'
export const LOAD_READMODEL_STATE_FAILURE =
  '@@resolve/LOAD_READMODEL_STATE_FAILURE'

export const APPLY_READMODEL_DIFF = '@@resolve/APPLY_READMODEL_DIFF'

export const DROP_READMODEL_STATE = '@@resolve/DROP_READMODEL_STATE'

//

export const HOT_MODULE_REPLACEMENT = '@@resolve/HOT_MODULE_REPLACEMENT'
