export const TODO_LIST_CREATED = 'TODO_LIST_CREATED'

export const TODO_LIST_RENAMED = 'TODO_LIST_RENAMED'

export const TODO_LIST_REMOVED = 'TODO_LIST_REMOVED'

export const TODO_ITEM_CREATED = 'TODO_ITEM_CREATED'

export const TODO_ITEM_TOGGLED = 'TODO_ITEM_TOGGLED'

export const TODO_ITEM_REMOVED = 'TODO_ITEM_REMOVED'
